config/routes.rb
Tareas::Application.routes.draw do
  match 'sesiones' => 'sesiones#new', as: 'nueva_sesion', via: :get
  match 'sesiones' => 'sesiones#create', via: :post
  match 'sesiones' => 'sesiones#destroy', as: 'cerrar_sesion', via: :delete

  resources :responsables do
    resources :tareas, only: [:index]
  end

  resources :tareas do
    put :completa, on: :member
  end

  root to: 'sesiones#new'

end

app/models/tarea.rb
class Tarea < ActiveRecord::Base
  attr_accessor :auto_responsable
  attr_accessible :nombre, :detalles, :fecha, :completa, :responsable_id,
    :auto_responsable

  validates :nombre, presence: true

  belongs_to :responsable

  def to_s
    self.nombre
  end

  def completa!
    self.update_attributes! completa: true
  end

  def self.recordar_vencimientos
    tareas = Tarea.where(
      [
        'fecha BETWEEN :hoy AND :futuro',
        'responsable_id IS NOT NULL',
        'completa = :false'
      ].join(' AND '),
      hoy: Date.today,
      futuro: 3.days.from_now.to_date,
      false: false
    )

    tareas.each do |tarea|
      TareasMailer.tarea_cercana(tarea).deliver
    end
  end
end

app/controllers/tareas_controller.rb
class TareasController < ApplicationController
  before_filter :requerir_responsable

  layout ->(c) { c.request.xhr? ? false : 'application' }

  # GET /tareas
  # GET /tareas.json
  def index
    if params[:responsable_id]
      @responsable = Responsable.find(params[:responsable_id])
      @tareas = @responsable.tareas
    else
      @tareas = Tarea.scoped
    end

    @tareas = @tareas.page(params[:page]).order('fecha ASC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tareas }
    end
  end

  # GET /tareas/1
  # GET /tareas/1.json
  def show
    @tarea = Tarea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tarea }
    end
  end

  # GET /tareas/new
  # GET /tareas/new.json
  def new
    @tarea = Tarea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tarea }
    end
  end

  # GET /tareas/1/edit
  def edit
    @tarea = Tarea.find(params[:id])
  end

  # POST /tareas
  # POST /tareas.json
  def create
    @tarea = Tarea.new(params[:tarea])

    respond_to do |format|
      if @tarea.save
        format.html { redirect_to @tarea, notice: t('tareas.creada') }
        format.json { render json: @tarea, status: :created, location: @tarea }
      else
        format.html { render action: "new" }
        format.json { render json: @tarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tareas/1
  # PUT /tareas/1.json
  def update
    @tarea = Tarea.find(params[:id])

    respond_to do |format|
      if @tarea.update_attributes(params[:tarea])
        format.html { redirect_to @tarea, notice: t('tareas.actualizada') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tareas/1
  # DELETE /tareas/1.json
  def destroy
    @tarea = Tarea.find(params[:id])
    @tarea.destroy

    respond_to do |format|
      format.html { redirect_to tareas_url }
      format.json { head :no_content }
    end
  end

  # PUT /tareas/1/completa
  # PUT /tareas/1/completa.json
  def completa
    @tarea = Tarea.find(params[:id])
    @tarea.completa!

    if request.xhr?
      render partial: 'tarea', locals: { tarea: @tarea }
    else
      respond_to do |format|
        format.html { redirect_to tareas_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/tareas_helper.rb
module TareasHelper
  def show_tarea_responsable_select(form)
    form.input(
      :responsable_id,
      collection: Responsable.all.map { |r| [r.to_s, r.id] },
      prompt: true
    )
  end
end

app/views/tareas/_form.html.erb
<%= simple_form_for(@tarea) do |f| %>
  <%= f.error_notification %>

  <%= f.input :nombre %>
  <%= f.input :fecha %>
  <%= f.input(
    :auto_responsable, label: Tarea.human_attribute_name('responsable_id'),
    input_html: {
      data: {
        'autocomplete-field' => true,
        'autocomplete-for' => '#tarea_responsable_id',
        'autocomplete-url' => responsables_path(format: :json)
      }
    }
  ) %>
  <%= f.input :responsable_id, as: :hidden %>
  <%= f.input :detalles, input_html: { rows: 5 } %>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary' %>
  </div>
<% end %>

app/views/tareas/_tarea.html.erb
<tr <%= raw 'class="strike"' if tarea.completa %>>
  <td><%= link_to tarea.nombre, tarea %></td>
  <td><%= tarea.fecha ? l(tarea.fecha) : '-' %></td>
  <td><%= tarea.responsable || '-' %></td>
  <td>
    <%= link_to(
      t('.completa'), completa_tarea_path(tarea, format: :html),
      method: :put, data: { 'remote' => true, 'completar-tarea' => true }
    ) unless tarea.completa %>
  </td>
</tr>

app/views/tareas/edit.html.erb
<div class="page-header">
  <h1><%= t('.titulo') %></h1>
  <nav>
    <%= link_to t('etiqueta.ver'), @tarea %> |
    <%= link_to t('etiqueta.volver'), tareas_path %>
  </nav>
</div>

<%= render 'form' %>

app/views/tareas/index.html.erb
<table class="table table-bordered table-striped table-condensed">
  <caption>
    <br />
    <h2><%= t('.titulo') %></h2>
    <br />
  </caption>
  <tr>
    <th><%= Tarea.human_attribute_name 'nombre' %></th>
    <th><%= Tarea.human_attribute_name 'fecha' %></th>
    <th><%= Tarea.human_attribute_name 'responsable_id' %></th>
    <th></th>
  </tr>

  <%= render partial: 'tarea', collection: @tareas %>
</table>

<br />

<%= will_paginate @tareas %>

<nav>
  <%= link_to t('.nueva'), new_tarea_path, class: 'btn btn-primary' %>
</nav>

app/views/tareas/new.html.erb
<div class="page-header">
  <h1><%= t('.titulo') %></h1>
  <nav>
    <%= link_to t('etiqueta.volver'), tareas_path %>
  </nav>
</div>

<%= render 'form' %>

app/views/tareas/show.html.erb
<br />

<section>
  <h1><%= @tarea.nombre %></h1>
  
  <% if @tarea.fecha %>
    <p>
      <strong><%= Tarea.human_attribute_name 'fecha' %></strong>:
      <%= l @tarea.fecha, format: :long %>
    </p>
  <% end %>

  <% if @tarea.responsable %>
    <p>
      <strong><%= Tarea.human_attribute_name 'responsable_id' %></strong>:
      <%= @tarea.responsable %>
    </p>
  <% end %>

  <%= simple_format @tarea.detalles %>
</section>

<nav class="form-actions">
  <%= link_to t('etiqueta.editar'), edit_tarea_path(@tarea), class: 'btn btn-primary' %>
  
  <div class="pull-right">
    <%= link_to t('etiqueta.eliminar'), @tarea, data: { confirm: t('mensaje.confirmacion') }, method: :delete %> |
    <%= link_to t('etiqueta.volver'), tareas_path %>
  </div>
</nav>