config/routes.rb
Tareas::Application.routes.draw do
  match 'sesiones' => 'sesiones#new', as: 'nueva_sesion', via: :get
  match 'sesiones' => 'sesiones#create', via: :post
  match 'sesiones' => 'sesiones#destroy', as: 'cerrar_sesion', via: :delete

  resources :responsables do
    resources :tareas, only: [:index]
  end

  resources :tareas do
    put :completa, on: :member
  end

  root to: 'sesiones#new'

end

app/views/comun/_menu.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        +
      </a>
      
      <a class="brand" href="#">Tareas</a>
 
      <div class="nav-collapse">
        <ul class="nav">
          <%= content_tag(
            :li,
            link_to('Tareas', tareas_path),
            class: ('active' if controller_name == 'tareas')
          ) %>
          <%= content_tag(
            :li,
            link_to('Responsables', responsables_path),
            class: ('active' if controller_name == 'responsables')
          ) %>
        </ul>
        <ul class="nav pull-right">
          <li>
            <%= link_to t('etiqueta.salir'), cerrar_sesion_path, method: :delete %>
          </li>
        </ul>
      </div>
 
    </div>
  </div>
</div>

app/views/comun/_notice.html.erb
<div id="notice" class="alert alert-success fade in">
  <a class="close" data-dismiss="alert" href="#">&times;</a>
  <%= flash.notice %>
</div>