config/routes.rb
Tareas::Application.routes.draw do
  match 'sesiones' => 'sesiones#new', as: 'nueva_sesion', via: :get
  match 'sesiones' => 'sesiones#create', via: :post
  match 'sesiones' => 'sesiones#destroy', as: 'cerrar_sesion', via: :delete

  resources :responsables do
    resources :tareas, only: [:index]
  end

  resources :tareas do
    put :completa, on: :member
  end

  root to: 'sesiones#new'

end

app/models/responsable.rb
# encoding: UTF-8
require 'digest/sha2'

class Responsable < ActiveRecord::Base
  # Ganchos
  before_save :asignar_clave_cifrada

  # Atributos no persistentes
  attr_accessor :clave

  attr_accessible :nombre, :email, :clave

  validates :nombre, presence: true

  has_many :tareas, dependent: :destroy

  def to_s
    self.nombre
  end

  def as_json(options = {})
    super({ only: [:id, :nombre] }.merge(options))
  end

  def generar_salt
    self.salt = Digest::SHA512.hexdigest(rand.to_s)
  end

  def asignar_clave_cifrada
    self.generar_salt if self.salt.blank?

    self.clave_cifrada = cifrar_clave(self.clave) if self.clave.present?
  end

  def cifrar_clave(clave)
    Digest::SHA512.hexdigest(self.salt.to_s + clave.to_s)
  end

  def clave_valida?(clave)
    self.clave_cifrada == cifrar_clave(clave)
  end

  def self.con_nombre(nombre)
    where("LOWER(#{table_name}.nombre) LIKE ?", "#{nombre}%".downcase)
  end
end

app/controllers/responsables_controller.rb
class ResponsablesController < ApplicationController
  before_filter :requerir_responsable

  # GET /responsables
  # GET /responsables.json
  def index
    @responsables = Responsable.order('nombre ASC').page(params[:page])
    @responsables = @responsables.con_nombre(params[:q]) if params[:q].present?

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @responsables }
    end
  end

  # GET /responsables/1
  # GET /responsables/1.json
  def show
    @responsable = Responsable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @responsable }
    end
  end

  # GET /responsables/new
  # GET /responsables/new.json
  def new
    @responsable = Responsable.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @responsable }
    end
  end

  # GET /responsables/1/edit
  def edit
    @responsable = Responsable.find(params[:id])
  end

  # POST /responsables
  # POST /responsables.json
  def create
    @responsable = Responsable.new(params[:responsable])

    respond_to do |format|
      if @responsable.save
        format.html { redirect_to @responsable, notice: 'Responsable creado' }
        format.json { render json: @responsable, status: :created, location: @responsable }
      else
        format.html { render action: 'new' }
        format.json { render json: @responsable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /responsables/1
  # PUT /responsables/1.json
  def update
    @responsable = Responsable.find(params[:id])

    respond_to do |format|
      if @responsable.update_attributes(params[:responsable])
        format.html { redirect_to @responsable, notice: 'Responsable actualizado' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @responsable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responsables/1
  # DELETE /responsables/1.json
  def destroy
    @responsable = Responsable.find(params[:id])
    @responsable.destroy

    respond_to do |format|
      format.html { redirect_to responsables_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/responsables_helper.rb
module ResponsablesHelper
end

app/views/responsables/_form.html.erb
<%= simple_form_for(@responsable) do |f| %>
  <%= f.error_notification %>

  <%= f.input :nombre %>
  <%= f.input :email %>
  <%= f.input :clave, as: :password %>
  
  <div class="actions">
    <%= f.button :submit, class: 'btn-primary' %>
  </div>
<% end %>

app/views/responsables/edit.html.erb
<div class="page-header">
  <h1><%= t('.titulo') %></h1>
  <nav>
    <%= link_to t('etiqueta.ver'), @responsable %> |
    <%= link_to t('etiqueta.volver'), responsables_path %>
  </nav>
</div>

<%= render 'form' %>

app/views/responsables/index.html.erb
<table class="table table-bordered table-striped table-condensed">
  <caption>
    <br />
    <h2><%= t('.titulo') %></h2>
    <br />
  </caption>
  
  <tr>
    <th><%= Responsable.human_attribute_name 'nombre' %></th>
    <th><%= Responsable.human_attribute_name 'email' %></th>
    <th><%= Tarea.model_name.human(count: 0) %></th>
  </tr>
  <% @responsables.each do |responsable| %>
    <tr>
      <td><%= link_to responsable.nombre, responsable %></td>
      <td><%= mail_to responsable.email %></td>
      <td><%= link_to t('.tareas'), responsable_tareas_path(responsable) %></td>
    </tr>
  <% end %>
</table>
<br />

<%= will_paginate @responsables %>

<nav>
  <%= link_to t('.nuevo'), new_responsable_path, class: 'btn btn-primary' %>
</nav>

app/views/responsables/new.html.erb
<div class="page-header">
  <h1><%= t('.titulo') %></h1>
  <nav>
    <%= link_to t('etiqueta.volver'), responsables_path %>
  </nav>
</div>

<%= render 'form' %>

app/views/responsables/show.html.erb
<br />

<h1><%= @responsable.nombre %></h1>

<p><%= mail_to @responsable.email %></p>

<nav class="form-actions">
  <%= link_to t('etiqueta.editar'), edit_responsable_path(@responsable) %> |
  <%= link_to t('etiqueta.eliminar'), @responsable, data: { confirm: t('mensaje.confirmacion') }, method: :delete %> |
  <%= link_to t('etiqueta.volver'), responsables_path %>
</nav>