config/routes.rb
Tareas::Application.routes.draw do
  match 'sesiones' => 'sesiones#new', as: 'nueva_sesion', via: :get
  match 'sesiones' => 'sesiones#create', via: :post
  match 'sesiones' => 'sesiones#destroy', as: 'cerrar_sesion', via: :delete

  resources :responsables do
    resources :tareas, only: [:index]
  end

  resources :tareas do
    put :completa, on: :member
  end

  root to: 'sesiones#new'

end

app/controllers/sesiones_controller.rb
# encoding: UTF-8

class SesionesController < ApplicationController
  before_filter :no_requerir_responsable, only: [:new, :create]
  before_filter :requerir_responsable, only: :destroy

  # GET /sesiones/new
  def new
    @responsable = Responsable.new

    respond_to do |format|
      format.html
      format.json { render json: @responsable }
    end
  end

  def create
    email, clave = params[:responsable][:email], params[:responsable][:clave]
    @responsable = Responsable.find_or_initialize_by_email(email)
    
    respond_to do |format|
      if @responsable && @responsable.clave_valida?(clave)
        session[:responsable_id] = @responsable.id

        format.html { redirect_to(tareas_url, notice: t('sesiones.ingreso_correcto')) }
      else
        flash.now.notice = t('sesiones.ingreso_incorrecto')

        format.html { render action: 'new' }
      end
    end
  end

  def destroy
    reset_session

    respond_to do |format|
      format.html { redirect_to nueva_sesion_url, notice: t('sesiones.sesion_cerrada') }
    end
  end
end

app/views/sesiones/new.html.erb
<br />

<div class="row">
  <div class="span4 offset4 well">
    <%= simple_form_for(@responsable, url: nueva_sesion_path, method: :post) do |f| %>
      <%= f.input :email, input_html: { class: 'span4', autofocus: true } %>
      <%= f.input :clave, as: :password, input_html: { class: 'span4' } %>

      <hr />
      <%= f.button :submit, t('.ingresar'), class: 'btn-primary' %>
    <% end %>
  </div>
</div>